"""durable student learning reports

Revision ID: 3aff386ca334
Revises: e7119448f3e4
Create Date: 2026-10-07 12:41:40.183078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aff386ca334'
down_revision: Union[str, Sequence[str], None] = 'e7119448f3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('active_key', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('phase', sa.String(length=255), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('lease_until', sa.DateTime(), nullable=True),
    sa.Column('lease_token', sa.String(length=64), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('checkpoint', sa.JSON(), nullable=False),
    sa.Column('counts', sa.JSON(), nullable=False),
    sa.Column('models', sa.JSON(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('active_key')
    )
    op.create_index(op.f('ix_learning_reports_course_id'), 'learning_reports', ['course_id'], unique=False)
    op.create_index(op.f('ix_learning_reports_lease_until'), 'learning_reports', ['lease_until'], unique=False)
    op.create_index(op.f('ix_learning_reports_status'), 'learning_reports', ['status'], unique=False)
    op.create_index(op.f('ix_learning_reports_student_id'), 'learning_reports', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_reports_student_id'), table_name='learning_reports')
    op.drop_index(op.f('ix_learning_reports_status'), table_name='learning_reports')
    op.drop_index(op.f('ix_learning_reports_lease_until'), table_name='learning_reports')
    op.drop_index(op.f('ix_learning_reports_course_id'), table_name='learning_reports')
    op.drop_table('learning_reports')
    # ### end Alembic commands ###
