"""editable course documentation and history

Revision ID: c8bc885e0192
Revises: da4d8d246ec0
Create Date: 2026-10-07 19:21:02.050930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8bc885e0192'
down_revision: Union[str, Sequence[str], None] = 'da4d8d246ec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_document_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_key', sa.String(length=150), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('edited_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_key'], ['site_courses.key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_key', 'path', 'revision')
    )
    op.create_table('site_documents',
    sa.Column('site_key', sa.String(length=150), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('edited_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_key'], ['site_courses.key'], ),
    sa.PrimaryKeyConstraint('site_key', 'path')
    )
    op.create_table('site_files',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('site_key', sa.String(length=150), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['site_key'], ['site_courses.key'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_files')
    op.drop_table('site_documents')
    op.drop_table('site_document_revisions')
    # ### end Alembic commands ###
