"""course assistants and documentation site integration

Revision ID: da4d8d246ec0
Revises: 3aff386ca334
Create Date: 2026-10-07 18:34:00.902215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da4d8d246ec0'
down_revision: Union[str, Sequence[str], None] = '3aff386ca334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_assistants',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'student_id')
    )
    op.create_table('site_courses',
    sa.Column('key', sa.String(length=150), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('open_enrollment', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('key'),
    sa.UniqueConstraint('course_id')
    )
    op.create_table('site_course_topics',
    sa.Column('site_key', sa.String(length=150), nullable=False),
    sa.Column('session', sa.String(length=20), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_key'], ['site_courses.key'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('site_key', 'session'),
    sa.UniqueConstraint('topic_id')
    )
    op.create_table('resource_origins',
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=1000), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('resource_id'),
    sa.UniqueConstraint('course_id', 'source_key')
    )
    op.create_table('topic_readings',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('topic_id', 'resource_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic_readings')
    op.drop_table('resource_origins')
    op.drop_table('site_course_topics')
    op.drop_table('site_courses')
    op.drop_table('course_assistants')
    # ### end Alembic commands ###
