"""teacher forms quizzes and chat topic selections

Revision ID: e7119448f3e4
Revises: 7c4e910
Create Date: 2026-10-07 12:20:43.344115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7119448f3e4'
down_revision: Union[str, Sequence[str], None] = '7c4e910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('topic_ids', sa.JSON(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_forms_course_id'), 'report_forms', ['course_id'], unique=False)
    op.create_table('teaching_quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teaching_quizzes_course_id'), 'teaching_quizzes', ['course_id'], unique=False)
    op.create_table('chat_topic_selections',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_chat_topic_selections_topic_id'), 'chat_topic_selections', ['topic_id'], unique=False)
    op.create_table('teaching_quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('expired', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['teaching_quizzes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quiz_id', 'student_id')
    )
    op.create_index(op.f('ix_teaching_quiz_attempts_quiz_id'), 'teaching_quiz_attempts', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_teaching_quiz_attempts_student_id'), 'teaching_quiz_attempts', ['student_id'], unique=False)
    op.create_table('teaching_quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_choice', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['teaching_quizzes.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teaching_quiz_questions_quiz_id'), 'teaching_quiz_questions', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_teaching_quiz_questions_topic_id'), 'teaching_quiz_questions', ['topic_id'], unique=False)
    op.create_table('report_form_entries',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['report_forms.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['self_reports.id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_report_form_entries_form_id'), 'report_form_entries', ['form_id'], unique=False)
    op.create_table('teaching_quiz_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['teaching_quiz_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['teaching_quiz_questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id')
    )
    op.create_index(op.f('ix_teaching_quiz_answers_attempt_id'), 'teaching_quiz_answers', ['attempt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teaching_quiz_answers_attempt_id'), table_name='teaching_quiz_answers')
    op.drop_table('teaching_quiz_answers')
    op.drop_index(op.f('ix_report_form_entries_form_id'), table_name='report_form_entries')
    op.drop_table('report_form_entries')
    op.drop_index(op.f('ix_teaching_quiz_questions_topic_id'), table_name='teaching_quiz_questions')
    op.drop_index(op.f('ix_teaching_quiz_questions_quiz_id'), table_name='teaching_quiz_questions')
    op.drop_table('teaching_quiz_questions')
    op.drop_index(op.f('ix_teaching_quiz_attempts_student_id'), table_name='teaching_quiz_attempts')
    op.drop_index(op.f('ix_teaching_quiz_attempts_quiz_id'), table_name='teaching_quiz_attempts')
    op.drop_table('teaching_quiz_attempts')
    op.drop_index(op.f('ix_chat_topic_selections_topic_id'), table_name='chat_topic_selections')
    op.drop_table('chat_topic_selections')
    op.drop_index(op.f('ix_teaching_quizzes_course_id'), table_name='teaching_quizzes')
    op.drop_table('teaching_quizzes')
    op.drop_index(op.f('ix_report_forms_course_id'), table_name='report_forms')
    op.drop_table('report_forms')
    # ### end Alembic commands ###
